### ISSUE TITLE
support `update` command

### ISSUE THREAD

**Issue by intrand** [ivanfetch/jkl#1]
I would like the ability to update the tool from within the tool (eg, `jkl update`). There are several Go projects to choose from which offer this functionality.

**Comment by ivanfetch** [comment]
Thanks for using jkl, and providing feedback!

This is now available in [release 0.0.8](https://github.com/ivanfetch/jkl/releases/tag/v0.0.8). The `jkl update` command updates the running binary to the latest release, and the `jkl version` command will now notify if a newer release is available.
